/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taskmanager.gui;

import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.text.*;
import javax.swing.JOptionPane;
import taskmanager.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.xml.stream.XMLStreamException;
/**
 *
 * @author Настя
 */
public class SetTaskFrame extends JDialog {
 
    private String name;
    private String description;
    private Date time;
    private String contacts;   
    private Task task;
    ClientWorkTaskList workTaskList;
    public final int SAVE = 1;
    public final int CANCEL = 0;
    int state;
    
    public SetTaskFrame() {
        this.setSize(360, 500);
        initComponents();
    }
   
    public SetTaskFrame(Task task){
        this.setSize(360, 500);
        if (task != null) {
            name = task.getName();
            description = task.getDescription();
            time = task.getTime();
            contacts = task.getContacts();
        } 
        initComponents();
        
    }
    public SetTaskFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setSize(360, 500);
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        cencelButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        contactsLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        taskNameLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        taskNameTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        descriptionTextField = new javax.swing.JTextField();
        contactsTextField = new javax.swing.JTextField();

        jInternalFrame1.setVisible(true);

        cencelButton.setText("Сancel");
        cencelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cencelButtonMouseClicked(evt);
            }
        });

        SaveButton.setText("Save");
        SaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveButtonMouseClicked(evt);
            }
        });
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        contactsLabel.setText("Contacts");

        descriptionLabel.setText("Description");

        taskNameLabel.setText("Task Name");

        dateLabel.setText("Date and Time");

        taskNameTextField.setText("task1");
        if (name != null) {
            taskNameTextField.setText(name);
        }

        dateTextField.setText("dd.MM.yyyy HH:mm");
        if (time != null) {
            dateTextField.setText(time.toString());
        }

        descriptionTextField.setText("Enter the information abaut task");
        if (description != null) {
            descriptionTextField.setText(description);
        }
        descriptionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionTextFieldActionPerformed(evt);
            }
        });

        contactsTextField.setText("Enter the contacts");
        if (contacts != null) {
            contactsTextField.setText(contacts);
        }

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(dateLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(taskNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(taskNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(descriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                    .addComponent(cencelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(68, 68, 68)
                                    .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(contactsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(descriptionTextField)
                                .addComponent(contactsTextField)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(taskNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taskNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(descriptionLabel)
                .addGap(18, 18, 18)
                .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contactsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cencelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cencelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cencelButtonMouseClicked
        state = CANCEL;
        this.setVisible(false);
    }//GEN-LAST:event_cencelButtonMouseClicked

    private void SaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveButtonMouseClicked
        try { 
            name = taskNameTextField.getText();
            String stringDateFormat = "dd.MM.yyyy HH:mm";
            SimpleDateFormat format = new SimpleDateFormat(stringDateFormat);
            String date= dateTextField.getText();
            if (check(date)==false){
                JOptionPane.showMessageDialog(this, "Incorrect data! Please, try again!");
            }else{
                time = format.parse(dateTextField.getText());
                Date data= new Date();
                if (data.compareTo(time)>0){
                    JOptionPane.showMessageDialog(this, "This day has already passed! Please, enter a future day!");
                }else {
                    description = descriptionTextField.getText();
                    contacts = contactsTextField.getText();
                    task = new Task(name, description, time, contacts);
                    try {
                        workTaskList = new ClientWorkTaskList();
                        workTaskList.addTask(task);
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(SetTaskFrame.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(SetTaskFrame.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (XMLStreamException ex) {
                        Logger.getLogger(SetTaskFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    this.setVisible(false);
                    state = SAVE;
                }
            }
        } catch (NumberFormatException exception) {
            JOptionPane.showMessageDialog(this, exception.getMessage());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Incorrect data! Please, try again!");
        }
    }//GEN-LAST:event_SaveButtonMouseClicked

    private void descriptionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionTextFieldActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
       
    }//GEN-LAST:event_SaveButtonActionPerformed

     private void formWindowClosing(WindowEvent evt) {                                   
        state = CANCEL;
    }                                                                                     

    public int showDialog() {
        setVisible(true);
        return state;
    }
    
    public String getTaskName(){
        return name;
    }
    
    public Date getDate(){
        return time;
    }
    
    public String getDiscription(){
        return description;
    }
    
    public String getContacts(){
        return contacts;
    }

    public Task getTask(){
        return task;
    }
    public boolean check(String date){
        char[] e = date.toCharArray(); 
        int dd= Character.getNumericValue(e[0])*10+Character.getNumericValue(e[1]),
                mm=Character.getNumericValue(e[3])*10+Character.getNumericValue(e[4]), 
                yy=Character.getNumericValue(e[6])*1000+Character.getNumericValue(e[7])*100+Character.getNumericValue(e[8])*
                10+Character.getNumericValue(e[9]),
                hh=Character.getNumericValue(e[11])*10+Character.getNumericValue(e[12]), 
                min=Character.getNumericValue(e[14])*10+Character.getNumericValue(e[15]);
        
        if (dd>31|| dd<0|| mm>12||mm<0||yy>2017||hh>24||hh<0||min>59||min<0|| e.length!=16){
            return false;
        } else{ 
            return true;
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                SetTaskFrame sf = new SetTaskFrame();
                sf.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosing(WindowEvent e) {
                        System.exit(0);
                    }
                });
                sf.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton cencelButton;
    private javax.swing.JLabel contactsLabel;
    private javax.swing.JTextField contactsTextField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel taskNameLabel;
    private javax.swing.JTextField taskNameTextField;
    // End of variables declaration//GEN-END:variables
}
